#项目相关配置
ty:
  initPassword: 123456 #用户的初始密码
  lang: lang #本地化语言的Cookie标识

#默认使用生产环境配置
#https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4
spring:
  profiles:
    include: shiro-rules,view-mapping
    active: prod