shiro:
  web:
    rules: "
      /index = authc \n
      /**/view = authc \n
      /system/user/secure/check = authc \n
      /system/user/password/update = authc \n
      /system/user/grant/can/list/* = authc \n
      /system/user/profile/** = authc \n
      /system/role/grant/list/* = authc \n
      /system/dict/single/* = authc \n
      /system/dict/items = authc \n
      /system/menu/user/list = perms[authc] \n
      /stomp/** = authc \n
      /** = perms[url] \n
    "
    ignoreUrls:
      - "/"
      - "/lang/list"
      - "/lang/resources"
      - "/**/*.ico"
      - "/**/*.jpg"
      - "/**/*.png"
      - "/**/*.gif"
      - "/**/*.bmp"
      - "/**/*.svg"
      - "/**/*.woff"
      - "/**/*.woff2"
      - "/**/*.ttf"
      - "/**/*.eot"
      - "/**/*.css"
      - "/**/*.js"
      - "/**/*.json"
      - "/**/*.map"
      - "/**/*.html"
      - "/**/*.pdf"
      - "/**/*.xlsx"
      - "/**/*.docx"
      - "/fonts/**"
      - "/error/**"

